version: "3.0"

services:

  app:
    build: .
    container_name: "${APP_NAME}.app"
    ports:
      - 9000:9000
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - redis
    networks:
      - default

  nginx:
    image: nginx:1.25.3
    container_name: "${APP_NAME}.nginx"
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - default

  db:
    image: mysql:8.2.0
    container_name: "${APP_NAME}.mysql"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    networks:
      - default

  redis:
    image: redis:7.2.2
    container_name: "${APP_NAME}.redis"
    restart: always
    ports:
      - 6379:6379
    networks:
      - default

  adminer:
    image: adminer:4.8.1
    container_name: "${APP_NAME}.adminer"
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - default

volumes:

  data:

networks:

  default:
    name: "${APP_NAME}.network"
